// import Navbar from '@/componet/Navbar'

import './globals.css'
import { Inter } from 'next/font/google'
import Prvider from '@/Redux/Prvider'
import Navbar from './components/navbar/page'
import MyState from '@/context/myState'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Script from 'next/script'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyState>
      <Head>
          ...
      	<script
            src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js"
            async
          ></script>
          <script
            src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/Observer.min.js"
            async
          ></script>
        </Head>
      <body className={inter.className}>
      {/* <Script src=""></Script> */}
      <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>
      <Prvider>
      <Navbar/>
      {children}
      {/* {children} */}
      <ToastContainer/>
      </Prvider>
      </body>
      </MyState>
    </html>
  )
}
