'use client'
import React,{useState,useEffect} from 'react';
import Home from './pages/home/page';
import Router from 'next/router'
import LoadingBar from 'react-top-loading-bar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Page = () => {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
   setProgress(1000);
  },[]);
  return (
    <div>
      {/* <LoadingBar
        color='#f11946'
        progress={progress}
        onLoaderFinished={() => setProgress(0)}
        /> */}
        <Home/>
    </div>
  );
}

export default Page;
